./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 8 8
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 4 4 
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 2 2
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 
./smallpt_thread_pool 1 1 